docs(docs): create a separate section for doc generation
ionic-team/stencil-site pull request #1090
Opened 2023-04-07 13:52 UTC by rwaskiewicz

2023-04-07 14:17 UTC, rwaskiewicz commented
@JessicaSachs I added you for general viz, no pressure to review while you're onboarding

2023-04-12 13:58 UTC, tanner-reits commented
I don't have any concerns or objections with this. It'd be nice if we could nest this under "output targets", but that would negate surfacing this for visibility. 

One side note semi-related to this is the distinction between `custom` and `docs-custom`. I don't believe we document the `custom` target anywhere. But, if we wanted to change that, we'd need to add clarity around their use-cases since `custom` accepts a `docs` param for its `generator` function.

2023-04-12 14:16 UTC, alicewriteswrongs requested changes
One question about the text while we're in here (I know this is only showing up as green as an artifact of the move)

I like the move overall and think it will surface documentation generation as a feature of Stencil more to the reader!

Unrelated to whether this is a good idea or not, I want to point out a little inconsistency in our sidebar:

<img width="275" alt="Screenshot 2023-04-12 at 10 09 42 AM" src="https://user-images.githubusercontent.com/6207644/231484056-358fabe1-76bb-4e13-a033-b4c7b9176553.png">

Basically one of the documentation output targets has a page title which looks like a title ("VS Code Documentation") while the others have the names of the output targets ("docs-json", "docs-custom", etc).

Should we standardize one way or the other?

Personally I think I might find it a little more inviting if they were titled like so:

<img width="285" alt="Screenshot 2023-04-12 at 10 12 20 AM" src="https://user-images.githubusercontent.com/6207644/231484839-230631a5-a195-4122-bb10-b41f2ae974c6.png">

I don't know what the exact titles are there, but it might be nice to have something like that, especially because after moving these out from under the "Output Targets" heading it may not be clear to the reader that a title like `docs-json` is the output target type that you'd use for doing JSON documentation output.

Another way to put this is that if they're living in a separate section for Documentation Generation, then conceptually those pages are no longer documentation _for specific output targets_ but instead generally covering how to use Stencil to generate, say, documentation in the JSON format. The fact that that is done w/ an output target, configured in the Stencil configuration, is something of an implementation detail — maybe in the future we'd have a page here for something which is not output target-driven but instead used via the CLI, for instance.

In summary, thank you for coming to my TED talk about how to overthink small changes 😅

2023-04-12 14:16 UTC, alicewriteswrongs commented on docs/documentation-generation/01-overview.md
> +As apps scale with more and more components, and team size and members continue to adjust over time, it's vital all components are well documented, and that the documentation itself is maintained. Ma
I sort of like writing documentation / technical things! It's a great way to clarify ideas and present how something works - I'd kind of like it if we could remove / change the wording here that suggests it's boring or a chore to write documentation — I know many developers do feel that way though, so maybe we could say something more like

"Whether you love taking the time to write documentation or you can't wait to get coding again, we could all use some help in keeping documentation up-to-date when we change components and APIs. Stencil provides some built-in tools to automate extracting information from your component library, providing flexible output formats that you can use when building out your library's documentation."

Idk if that quite rolls of the tongue, but something along those lines?

2023-04-14 13:18 UTC, rwaskiewicz commented
Does anyone have any qualms with us _just_ updating `next` and `v3.2`? I wonder if a refactor of this size (including updating titles, copy, etc.) should just be limited to the latest versions of the docs

2023-04-14 13:49 UTC, alicewriteswrongs commented
yeah I think that makes sense, we can make changes like this and have them apply going forward, but no need to rewrite history :)

2023-04-18 15:12 UTC, tanner-reits approved these changes
I'm onboard to only change 3.2 and next. Deployment looks good in that regard 👍

2023-04-28 15:24 UTC, alicewriteswrongs approved these changes
thought I had already approved, sorry about that!

2023-04-28 18:08 UTC, merged