docs(docs-json): add explanation of new `supplementalPublicTypes` option
ionic-team/stencil-site pull request #1146
Opened 2023-06-14 19:23 UTC by alicewriteswrongs

2023-06-21 13:13 UTC, tanner-reits approved these changes
Think this is a good starting point. One question:

If a type in the file for `supplementalPublicTypes` is referenced in a component's prop/event, it will still only create one entry in the `typeLibrary`, correct? Maybe I'll answer my own question when I review the code changes associated with this more thoroughly 😅

2023-06-21 15:37 UTC, alicewriteswrongs commented
@tanner-reits yes, that is the idea! Basically each type has a unique ID based on the file in which it's declared and its name and it will have a single entry associated with it in the type lbirary

2023-06-22 13:31 UTC, rwaskiewicz requested changes

2023-06-22 15:01 UTC, alicewriteswrongs commented on docs/documentation-generation/docs-json.md
> +
sure, makes sense - I'll add a few sentences breaking it down

2023-06-26 13:09 UTC, merged