docs(wrappers): add `enableImportInjection` to FAQ
ionic-team/stencil-site pull request #1189
Opened 2023-07-25 14:32 UTC by tanner-reits

Updates the documentation for the React and Vue output targets to include a FAQ entry for users encountering a "cannot read property of undefined (reading `isProxied`)".

Also updates some config diffs to make packages publishable.

2023-07-26 21:03 UTC, alicewriteswrongs requested changes

2023-07-26 21:03 UTC, alicewriteswrongs commented on docs/framework-integration/react.md
> +### TypeError: Cannot read propertied of undefined (reading 'isProxied')
```suggestion
### TypeError: Cannot read property of undefined (reading 'isProxied')
```

2023-07-26 21:03 UTC, alicewriteswrongs commented on versioned_docs/version-v2/framework-integration/react.md
> +### TypeError: Cannot read propertied of undefined (reading 'isProxied')
```suggestion
### TypeError: Cannot read property of undefined (reading 'isProxied')
```

just same thing as above here

2023-07-26 21:03 UTC, alicewriteswrongs commented on versioned_docs/version-v2/framework-integration/vue.md
> +### TypeError: Cannot read propertied of undefined (reading 'isProxied')
```suggestion
### TypeError: Cannot read property of undefined (reading 'isProxied')
```

sorry for repetition 😭

2023-07-26 21:03 UTC, alicewriteswrongs commented on versioned_docs/version-v2/framework-integration/vue.md
> +### TypeError: Cannot read propertied of undefined (reading 'isProxied')
ok there's a few more - I'll trust you to find them!

2023-07-26 21:12 UTC, tanner-reits commented on docs/framework-integration/react.md
> +### TypeError: Cannot read propertied of undefined (reading 'isProxied')
🤦

2023-07-26 21:30 UTC, alicewriteswrongs approved these changes

2023-07-27 12:14 UTC, rwaskiewicz approved these changes

2023-07-27 12:14 UTC, rwaskiewicz commented on docs/framework-integration/react.md
>  +  },
And [here](https://github.com/ionic-team/stencil-site/pull/1189/files#diff-d02abf1cd9aa8d2437a685d63c50088400c1cb61dee1c9a6842579282d5aeeaaL148) 😢

2023-07-27 12:14 UTC, rwaskiewicz commented on versioned_docs/version-v3/framework-integration/react.md
> +:::note
Nice 👍

2023-07-27 13:30 UTC, merged