docs(config): add documentation for `hydratedFlag`
ionic-team/stencil-site pull request #1345
Opened 2024-02-05 20:22 UTC by alicewriteswrongs

This adds documentation for the `hydratedFlag` config option, which controls how Stencil marks hydration on components.

fixes #882
STENCIL-1045

2024-02-05 20:24 UTC, alicewriteswrongs reviewed
few quick notes

2024-02-05 20:24 UTC, alicewriteswrongs commented on docs/config/01-overview.md
> +The supported options are as follows:
I based the documentation for the sub-options on what I found here: https://github.com/ionic-team/stencil/blob/4d9c73cc5c19d4cc7ff330e078cfddb063173724/src/declarations/stencil-public-compiler.ts#L510-L536

2024-02-05 20:24 UTC, alicewriteswrongs commented on docs/config/01-overview.md
> +Stencil will automatically generate the following default configuration:
I based this on https://github.com/ionic-team/stencil/blob/4d9c73cc5c19d4cc7ff330e078cfddb063173724/src/declarations/stencil-public-compiler.ts#L210-L219

2024-02-05 20:24 UTC, alicewriteswrongs commented on docs/config/01-overview.md
> +}
based on https://github.com/ionic-team/stencil/blob/4d9c73cc5c19d4cc7ff330e078cfddb063173724/src/compiler/config/test/validate-hydrated.spec.ts#L28-L34 and reading through [`src/compiler/config/validate-hydrated.ts`](https://github.com/ionic-team/stencil/blob/4d9c73cc5c19d4cc7ff330e078cfddb063173724/src/compiler/config/validate-hydrated.ts#L1)

2024-02-06 06:19 UTC, christian-bromann approved these changes
👍

2024-02-06 15:25 UTC, tanner-reits requested changes
Can we add a callout of some kind that this is only for the lazy build?

2024-02-06 16:00 UTC, alicewriteswrongs commented
updated that!

2024-02-06 16:08 UTC, tanner-reits approved these changes
Looks good. We'll probably wanna propagate this to previous versions (at least v4).

This did get me questioning if this can/should be moved to the lazy-build specifically (both in the code and docs), but we can figure that out later.

2024-02-06 16:48 UTC, merged