Update 01-overview.md
ionic-team/stencil-site pull request #1370
Opened 2024-03-08 18:11 UTC by eriklharper

correcting spelling error on line 40

2024-03-08 18:29 UTC, alicewriteswrongs requested changes
thanks for finding this typo!

would you mind also updating the file at `docs/output-targets/01-overview.md`? the docs in `docs/` are the 'next' docs which will be used as the basis for future versions, so we want to make sure changes like this are made in there as well so that they'll be applied to future versions of the docs.

If you're up for it you could also fix this in earlier versions too! It looks like we've had the typo for a while.

2024-03-08 19:50 UTC, eriklharper commented
https://github.com/ionic-team/stencil-site/pull/1370

2024-03-11 12:58 UTC, rwaskiewicz approved these changes

2024-03-11 13:55 UTC, alicewriteswrongs approved these changes

2024-03-11 13:56 UTC, merged