docs(vitest): add Vitest option to testing section
ionic-team/stencil-site pull request #1407
Opened 2024-04-18 22:05 UTC by christian-bromann

This patch adds another option for testing Stencil components using Vitest. While this option has its limitation (no auto-waits and no mocking) it still is an option that is useable and worth to document.

2024-05-08 15:36 UTC, alicewriteswrongs requested changes
a good addition I think! Just noticed a few things we might want to tweak

2024-05-08 15:36 UTC, alicewriteswrongs commented on docs/testing/03-vitest.md
> +Once you've setup Vitest you can start write your first test. In order to render a Stencil component into the browser, all you need to do is importing the component and initiating an instance of the
```suggestion
Once you've setup Vitest you can start write your first test. In order to render a Stencil component into the browser, all you need to do is import the component and initiate an instance of the component on the page:
```

2024-05-08 15:36 UTC, alicewriteswrongs commented on docs/testing/03-vitest.md
> +// src/components/my-component/my-component.test.ts
we could use the little `title` option like so if we want here:

````suggestion
```ts title="src/components/my-component/my-component.test.ts"
````

that goes for the other filenames in here as well

2024-05-08 15:36 UTC, alicewriteswrongs commented on docs/testing/03-vitest.md
> +```
we can also put the `npm2yarn` directive on here

````suggestion
```bash npm2yarn
npm test
```
````

2024-05-08 15:36 UTC, alicewriteswrongs commented on docs/testing/03-vitest.md
> +:::
should this maybe be a `caution`? Maybe that's too alarmist haha

2024-05-08 15:45 UTC, christian-bromann commented
@alicewriteswrongs thanks for your feedback, addressed all comments.

2024-05-08 17:42 UTC, alicewriteswrongs approved these changes

2024-05-09 14:07 UTC, tanner-reits approved these changes

2024-05-09 15:20 UTC, merged