docs(copy-task): Add docs to copy task options
ionic-team/stencil-site pull request #1464
Opened 2024-07-18 22:50 UTC by christian-bromann

Adding docs for all parameters the copy task takes.

2024-07-19 14:35 UTC, gnbm approved these changes

2024-07-22 15:07 UTC, tanner-reits requested changes

2024-07-22 15:07 UTC, tanner-reits commented on versioned_docs/version-v4.0/output-targets/copy-tasks.md
> +#### `ignore`
We should omit `ignore` from all previous versions

2024-08-02 16:04 UTC, tanner-reits approved these changes

2024-08-05 17:16 UTC, merged