docs: Update react.md to include a fix for imports not being resolved.
ionic-team/stencil-site pull request #1498
Opened 2024-12-10 07:56 UTC by DanyaalMajid

Add additional instructions to properly export the dist directory to fix build issues in the react-library later on.

2024-12-10 17:53 UTC, christian-bromann commented
@DanyaalMajid thanks for the contributions!

Could you describe a little bit more the problem this documentation tries to address?

2024-12-11 04:00 UTC, DanyaalMajid commented
In the current versions of both `stencil` and the `stencil/react-output-target` packages, exporting react wrappers of components causes an issue whereby the import statement does not resolve, and the `react-library` fails to build due to unresolved modules.

This requires modifying the `package.json` for the `stencil-library` to include the proper export of the dist directory.

Also exporting each component manually is a redundant task, so i also added an export for all components generated in the components directory.

Ideally this change should be made in the stencil template repository which is used to create the stencil components project, feel free to include this there, meanwhile the updated docs should help.

The full error in the `react-library` when the dist folder is not exported properly:

```
lib/components/stencil-generated/components.ts:14:93 - error TS2307: Cannot find module 'stencil-library/dist/components/my-component.js' or its corresponding type declarations.

import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "stencil-library/dist/components/my-component.js";

```

2025-01-09 06:54 UTC, christian-bromann requested changes
One comment. Can we apply the change in all other versioned documents, e.g.

- `docs/framework-integration/react.md`
- `versioned_docs/version-v4.23/framework-integration/react.md`
- etc

2025-01-09 06:54 UTC, christian-bromann commented on versioned_docs/version-v4.22/framework-integration/react.md
> +##### Troubleshooting Component Imports
```suggestion
##### Component Imports
```

2025-01-09 07:17 UTC, DanyaalMajid commented on versioned_docs/version-v4.22/framework-integration/react.md
> +##### Troubleshooting Component Imports
I update my patch-1 branch to incorporate your suggestions, sorry if is not up to snuff, i am new to pull requests.

2025-01-09 23:58 UTC, christian-bromann approved these changes
LGTM 👍  Thanks a lot!

2025-01-09 23:58 UTC, merged