Update what-is-design-system.md
ionic-team/stencil-site pull request #741
Opened 2021-06-09 07:05 UTC by sdhandapani

instead of Increased, it should be reduced/decreased time to market

2021-06-30 17:00 UTC, rwaskiewicz requested changes

2021-06-30 17:00 UTC, rwaskiewicz commented on src/docs/design-systems/what-is-design-system.md
> +With a design system in place, its true value is revealed. The entire product development team is freed up to focus on what matters most: solving customer problems and delivering value. Additionally,
Good catch! I think the use of 'increased' was in reference to the cost savings, maybe it makes sense to add that adjective back like so:
```suggestion
With a design system in place, its true value is revealed. The entire product development team is freed up to focus on what matters most: solving customer problems and delivering value. Additionally, the avoidance of having teams working in parallel, recreating the same UI elements over and over,   has a real-world project impact in terms of reduced time to market and increased cost savings.
```
(this keeps your suggestion to used 'reduced' as well)

2021-06-30 22:22 UTC, senthildhandapani approved these changes
great, looks ok now

2021-07-01 12:43 UTC, rwaskiewicz approved these changes

2021-07-01 12:47 UTC, merged