docs(output-targets) Updates to three output target pages
ionic-team/stencil-site pull request #773
Opened 2021-09-22 18:58 UTC by splitinfinities

- modifies custom-elements-bundle docs
 - adds the custom-elements docs
 - adds docs-stats

2021-09-24 15:03 UTC, rwaskiewicz requested changes

2021-09-24 16:20 UTC, splitinfinities commented on src/assets/docs-structure.json
> +        "text": "dist",
It already renders like this on the site today.

2021-09-24 16:24 UTC, splitinfinities commented on src/assets/docs-structure.json
> +        "text": "dist",
And yes, I want to update all of these pages in this PR so please review them.

2021-09-29 15:37 UTC, rwaskiewicz approved these changes

2021-09-29 15:38 UTC, merged