docs(reactive-data): update @watch documentation
ionic-team/stencil-site pull request #913
Opened 2022-09-09 14:49 UTC by rwaskiewicz

2022-10-17 13:14 UTC, tanner-reits approved these changes
Good improvements! 👍

2022-10-17 13:41 UTC, alicewriteswrongs requested changes
just had one wording quesiton

2022-10-17 13:41 UTC, alicewriteswrongs commented on src/docs/components/reactive-data.md
> +In order to make changes to an array, non-mutable array operators should be used.
would it be potentially clearer to say something like "the prop or state member should be assigned to a new array, created using a method like `.map()` or `filter()`, the spread operator syntax, or simply a new array literal" ? I wouldn't want to potentially give the impression that just calling `.map` will be enough (the difference being that you need to assign the new array which is the return value of map).

2022-10-18 19:35 UTC, alicewriteswrongs approved these changes
lgtm!

2022-10-18 19:35 UTC, alicewriteswrongs commented on src/docs/components/reactive-data.md
> +In order to make changes to an array, non-mutable array operators should be used.
yup, I think it's good :)

2022-10-18 19:52 UTC, merged