Update resources-data.ts
ionic-team/stencil-site pull request #929
Opened 2022-10-30 15:38 UTC by randy-r

Hello Stencil Team,

Please let me know if I can add those resources to the site.
Awesome work by the way!

Thanks,
Randy.

2022-11-01 13:51 UTC, tanner-reits commented on src/components/resources-page/resources-data.ts
> +      description: 'Example website for the using the Stedux library',
```suggestion
      description: 'Example website for using the Stedux library',
```

2022-11-01 13:51 UTC, tanner-reits commented on src/components/resources-page/resources-data.ts
> +      description: 'Example website for the using the Stenimator library',
```suggestion
      description: 'Example website for using the Stenimator library',
```

2022-11-02 12:00 UTC, rwaskiewicz requested changes
Thanks @randy-r! 

The team and I had a few small nitpicks we found while reviewing the PR. Could you please take a look when you get a chance? Thanks again!

2022-11-02 12:00 UTC, rwaskiewicz commented on src/components/resources-page/resources-data.ts
> +    { title: 'Stenimator: Animation coordintor for elements leaving the DOM', url: 'https://github.com/randy-r/stenimator' }
```suggestion
    { title: 'Stenimator: Animation coordinator for elements leaving the DOM', url: 'https://github.com/randy-r/stenimator' }
```

2022-11-05 14:58 UTC, randy-r commented
Hi @rwaskiewicz !

I should thank you and the team!
I have addressed your suggestions and adjusted the image size as they were a bit off.

Cheers!

2022-11-07 12:57 UTC, rwaskiewicz approved these changes
LGTM! Thanks!

2022-11-07 12:58 UTC, merged