Rwaskiewicz/helmet dep
ionic-team/stencil-site pull request #938
Opened 2022-11-30 13:35 UTC by rwaskiewicz

2022-11-30 15:11 UTC, tanner-reits approved these changes

2022-12-06 16:17 UTC, alicewriteswrongs requested changes
Proposed change looks good, just was wondering about some of the re-flowed text which could be improved a little here and there.

2022-12-06 16:17 UTC, alicewriteswrongs commented on src/docs/static-site-generation/meta.md
> +Or meta tags can be added and updated no differently than using the usual DOM APIs found in the browser, such as `document.head` and `document.createElement('meta')`.
Possible rewording section (I know this was already here, but figure why not tweak a little if it's kinda odd)

```suggestion
Similarly, meta tags can be set using standard DOM APIs as found in the browser, such as `document.head` and `document.createElement('meta')`.
```

2022-12-06 16:17 UTC, alicewriteswrongs commented on src/docs/static-site-generation/meta.md
> +This mean your components runtime may already be able to do much of the custom work throughout prerendering.
```suggestion
For this reason, your component's runtime can take care of much of this custom work during prerendering.
```

2022-12-06 16:17 UTC, alicewriteswrongs commented on src/docs/static-site-generation/meta.md
> +That said, the Prerender Config also comes with many options that allows individual pages to be modified.
```suggestion
That said, the Prerender Config also includes options that allow individual pages to be modified arbitrarily during prerendering.
```

2022-12-06 16:17 UTC, alicewriteswrongs commented on src/docs/static-site-generation/meta.md
> +For example, the `afterHydrate(document, url)` hook can be used to update the parsed `document`, before it is serialized into an HTML string.
```suggestion
For example, the `afterHydrate(document, url)` hook can be used to update the parsed `document` before it is serialized into an HTML string.
```

2022-12-06 16:17 UTC, alicewriteswrongs commented on src/docs/static-site-generation/meta.md
> +The `document` argument can be used no different from the `document` found in a webpage, and the `url` argument is a `URL` location of the page being rendered.
```suggestion
The `document` argument is a [standard `Document`](https://developer.mozilla.org/en-US/docs/Web/API/Document), while the `url` argument is a [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL) for the location of the page being rendered.
```

2022-12-06 17:07 UTC, alicewriteswrongs approved these changes
lgtm!

2022-12-06 17:42 UTC, merged