docs(extras): update documentation to deprecation dynamicImportShim
ionic-team/stencil-site pull request #949
Opened 2022-12-13 20:53 UTC by alicewriteswrongs

This updates the documentation for the `dynamicImportShim` field to indicate that it's been deprecated in Stencil V3.

2022-12-13 21:01 UTC, rwaskiewicz requested changes

2022-12-13 21:05 UTC, alicewriteswrongs commented on src/docs/config/extras.md
> +supported, and hence this field is deprecated.
Sure, I like it!

2022-12-13 21:14 UTC, rwaskiewicz approved these changes

2022-12-15 15:21 UTC, tanner-reits approved these changes

2022-12-15 15:22 UTC, merged