docs(v3-upgrade): add note about deprecating `cssVarsShim`
ionic-team/stencil-site pull request #950
Opened 2022-12-13 21:43 UTC by alicewriteswrongs

This adds a note to the v3 upgrade guide about deprecating `extras.cssVarShim`.

**NOTE**: this PR has https://github.com/ionic-team/stencil-site/pull/948 as its base.

2022-12-14 20:07 UTC, tanner-reits requested changes

2022-12-14 20:07 UTC, tanner-reits commented on src/docs/introduction/upgrading-to-stencil-three.md
> +`stencil.config.ts`:
Part of this sounds a little weird to me. I think we should just copy-paste the same sentence used for `dynamicImportShim`. I don't see why we need different wording for essentially the same thing 🤷‍♂️

2022-12-14 21:32 UTC, alicewriteswrongs commented
Agreed, just pushed that change

2022-12-16 18:25 UTC, tanner-reits approved these changes

2022-12-16 19:24 UTC, merged